#!/bin/bash

# this file is part of the nil0x42's git repositories
# for the current version, take a look at:
# https://bitbucket.org/nil0x42/scripts

# Show the battery's current life state on laptops

# Usage: batlife

# Depends: acpi

# This is not a real script, but the stripped output is cleanest than
# the default acpi output, especially when calling it from tmux, conky
# or any other kind of program, to show the current battery life state.

acpi -b | cut -d' ' -f3-
