#!/usr/bin/env bash

# this file is part of the nil0x42's git repositories
# for the current version, take a look at:
# https://github.com/nil0x42/scripts

# Remove ansi colors from stdin

# Example: echo -e '\033[31m red text' | decolorize

sed -r "s/\x1B\[[0-9;]*?[m|K]//g"
