#!/usr/bin/env bash

# this file is part of the nil0x42's git repositories
# for the current version, take a look at:
# https://bitbucket.org/nil0x42/scripts

# `ps` command displaying god owner instead of uid owner for processes

ps xao gid,ppid,c,stime,tty,time,cmd \
    | awk 'BEGIN { oldFS = FS; FS = ":"; while (getline < "/etc/group") user[$3]=$1; FS = oldFS }; { $1 = user[$1]; printf "%-13s %-5s %-2s %-5s %-7s %-9s ", $1, $2, $3, $4, $5, $6; for(i=7;i<=NF;i++){printf "%s ", $i}; printf "\n"}'
