#!/bin/bash

# this file is part of the nil0x42's git repositories
# for the current version, take a look at:
# https://github.com/nil0x42/scripts

# Dump files opened by <COMMAND> process

# Usage: strace-files <COMMAND>

# Depends: strace, perl

strace -ff -e trace=file "$@" 2>&1 | perl -ne 's/^[^"]+"(([^\\"]|\\[\\"nt])*)".*/$1/ && print'
